<?php
if ( ! defined( 'ABSPATH' ) ) {
	exit; // Exit if accessed directly.
}

// All colors
return array(
    array('white', 'ffffff'),
    array('default', 'e1e5ec'),
    array('dark', '2f353b'),
    array('blue', '3598dc'),
    array('blue-madison', '578ebe'),
    array('blue-chambray', '2C3E50'),
    array('blue-ebonyclay', '22313F'),
    array('blue-hoki', '67809F'),
    array('blue-steel', '4B77BE'),
    array('blue-soft', '4c87b9'),
    array('blue-dark', '5e738b'),
    array('blue-sharp', '5C9BD1'),
    array('green', '32c5d2'),
    array('green-meadow', '1BBC9B'),
    array('green-seagreen', '1BA39C'),
    array('green-turquoise', '36D7B7'),
    array('green-haze', '44b6ae'),
    array('green-jungle', '26C281'),
    array('green-soft', '3faba4'),
    array('green-dark', '4DB3A2'),
    array('green-sharp', '2ab4c0'),
    array('grey', 'E5E5E5'),
    array('grey-steel', 'e9edef'),
    array('grey-cararra', 'fafafa'),
    array('grey-gallery', '555555'),
    array('grey-cascade', '95A5A6'),
    array('grey-silver', 'BFBFBF'),
    array('grey-salsa', 'ACB5C3'),
    array('grey-salt', 'bfcad1'),
    array('grey-mint', '525e64'),
    array('red', 'e7505a'),
    array('red-pink', 'E08283'),
    array('red-sunglo', 'E26A6A'),
    array('red-intense', 'e35b5a'),
    array('red-thunderbird', 'D91E18'),
    array('red-flamingo', 'EF4836'),
    array('red-soft', 'd05454'),
    array('red-haze', 'f36a5a'),
    array('red-mint', 'e43a45'),
    array('yellow', 'c49f47'),
    array('yellow-gold', 'E87E04'),
    array('yellow-casablanca', 'f2784b'),
    array('yellow-crusta', 'f3c200'),
    array('yellow-lemon', 'F7CA18'),
    array('yellow-saffron', 'F4D03F'),
    array('yellow-soft', 'c8d046'),
    array('yellow-haze', 'c5bf66'),
    array('yellow-mint', 'c5b96b'),
    array('purple', '8E44AD'),
    array('purple-plum', '8775a7'),
    array('purple-medium', 'BF55EC'),
    array('purple-studio', '8E44AD'),
    array('purple-wisteria', '9B59B6'),
    array('purple-seance', '9A12B3'),
    array('purple-intense', '8775a7'),
    array('purple-sharp', '796799'),
    array('purple-soft', '8877a9'),
);
?>